export const data = [
  {
    PROJECT: "Argon Design System",
    BUDGET: "500 USD",
    STATUS: "pending",
    USERS: "",
    COMPLETION: "60%",
  },
  {
    PROJECT: "Angular Now UI Kit PRO",
    BUDGET: "800 USD",
    STATUS: "completed",
    USERS: "",
    COMPLETION: "100%",
  },
  {
    PROJECT: "Black Dashboard",
    BUDGET: "150 USD",
    STATUS: "delayed",
    USERS: "",
    COMPLETION: "72%",
  },
  {
    PROJECT: "React Material Dashboard",
    BUDGET: "400 USD",
    STATUS: "on schedule",
    USERS: "",
    COMPLETION: "90%",
  },
  {
    PROJECT: "Vue Paper UI Kit PRO",
    BUDGET: "200 USD",
    STATUS: "completed",
    USERS: "",
    COMPLETION: "100%",
  },
  {
    PROJECT: "Argon Design System",
    BUDGET: "500 USD",
    STATUS: "pending",
    USERS: "",
    COMPLETION: "60%",
  },
  {
    PROJECT: "Angular Now UI Kit PRO",
    BUDGET: "800 USD",
    STATUS: "completed",
    USERS: "",
    COMPLETION: "100%",
  },
  {
    PROJECT: "Black Dashboard",
    BUDGET: "150 USD",
    STATUS: "delayed",
    USERS: "",
    COMPLETION: "72%",
  },
  {
    PROJECT: "React Material Dashboard",
    BUDGET: "400 USD",
    STATUS: "on schedule",
    USERS: "",
    COMPLETION: "90%",
  },
  {
    PROJECT: "Vue Paper UI Kit PRO",
    BUDGET: "200 USD",
    STATUS: "completed",
    USERS: "",
    COMPLETION: "100%",
  },
  {
    PROJECT: "Argon Design System",
    BUDGET: "500 USD",
    STATUS: "pending",
    USERS: "",
    COMPLETION: "60%",
  },
  {
    PROJECT: "Angular Now UI Kit PRO",
    BUDGET: "800 USD",
    STATUS: "completed",
    USERS: "",
    COMPLETION: "100%",
  },
  {
    PROJECT: "Black Dashboard",
    BUDGET: "150 USD",
    STATUS: "delayed",
    USERS: "",
    COMPLETION: "72%",
  },
  {
    PROJECT: "React Material Dashboard",
    BUDGET: "400 USD",
    STATUS: "on schedule",
    USERS: "",
    COMPLETION: "90%",
  },
  {
    PROJECT: "Vue Paper UI Kit PRO",
    BUDGET: "200 USD",
    STATUS: "completed",
    USERS: "",
    COMPLETION: "100%",
  },
  {
    PROJECT: "Argon Design System",
    BUDGET: "500 USD",
    STATUS: "pending",
    USERS: "",
    COMPLETION: "60%",
  },
  {
    PROJECT: "Angular Now UI Kit PRO",
    BUDGET: "800 USD",
    STATUS: "completed",
    USERS: "",
    COMPLETION: "100%",
  },
  {
    PROJECT: "Black Dashboard",
    BUDGET: "150 USD",
    STATUS: "delayed",
    USERS: "",
    COMPLETION: "72%",
  },
  {
    PROJECT: "React Material Dashboard",
    BUDGET: "400 USD",
    STATUS: "on schedule",
    USERS: "",
    COMPLETION: "90%",
  },
  {
    PROJECT: "Vue Paper UI Kit PRO",
    BUDGET: "200 USD",
    STATUS: "completed",
    USERS: "",
    COMPLETION: "100%",
  },

  {
    PROJECT: "Argon Design System",
    BUDGET: "500 USD",
    STATUS: "pending",
    USERS: "",
    COMPLETION: "60%",
  },
  {
    PROJECT: "Angular Now UI Kit PRO",
    BUDGET: "800 USD",
    STATUS: "completed",
    USERS: "",
    COMPLETION: "100%",
  },
  {
    PROJECT: "Black Dashboard",
    BUDGET: "150 USD",
    STATUS: "delayed",
    USERS: "",
    COMPLETION: "72%",
  },
  {
    PROJECT: "React Material Dashboard",
    BUDGET: "400 USD",
    STATUS: "on schedule",
    USERS: "",
    COMPLETION: "90%",
  },
  {
    PROJECT: "Vue Paper UI Kit PRO",
    BUDGET: "200 USD",
    STATUS: "completed",
    USERS: "",
    COMPLETION: "100%",
  },
  {
    PROJECT: "Argon Design System",
    BUDGET: "500 USD",
    STATUS: "pending",
    USERS: "",
    COMPLETION: "60%",
  },
  {
    PROJECT: "Angular Now UI Kit PRO",
    BUDGET: "800 USD",
    STATUS: "completed",
    USERS: "",
    COMPLETION: "100%",
  },
  {
    PROJECT: "Black Dashboard",
    BUDGET: "150 USD",
    STATUS: "delayed",
    USERS: "",
    COMPLETION: "72%",
  },
  {
    PROJECT: "React Material Dashboard",
    BUDGET: "400 USD",
    STATUS: "on schedule",
    USERS: "",
    COMPLETION: "90%",
  },
  {
    PROJECT: "Vue Paper UI Kit PRO",
    BUDGET: "200 USD",
    STATUS: "completed",
    USERS: "",
    COMPLETION: "100%",
  },
  {
    PROJECT: "Argon Design System",
    BUDGET: "500 USD",
    STATUS: "pending",
    USERS: "",
    COMPLETION: "60%",
  },
  {
    PROJECT: "Angular Now UI Kit PRO",
    BUDGET: "800 USD",
    STATUS: "completed",
    USERS: "",
    COMPLETION: "100%",
  },
  {
    PROJECT: "Black Dashboard",
    BUDGET: "150 USD",
    STATUS: "delayed",
    USERS: "",
    COMPLETION: "72%",
  },
  {
    PROJECT: "React Material Dashboard",
    BUDGET: "400 USD",
    STATUS: "on schedule",
    USERS: "",
    COMPLETION: "90%",
  },
  {
    PROJECT: "Vue Paper UI Kit PRO",
    BUDGET: "200 USD",
    STATUS: "completed",
    USERS: "",
    COMPLETION: "100%",
  },
  {
    PROJECT: "Argon Design System",
    BUDGET: "500 USD",
    STATUS: "pending",
    USERS: "",
    COMPLETION: "60%",
  },
  {
    PROJECT: "Angular Now UI Kit PRO",
    BUDGET: "800 USD",
    STATUS: "completed",
    USERS: "",
    COMPLETION: "100%",
  },
  {
    PROJECT: "Black Dashboard",
    BUDGET: "150 USD",
    STATUS: "delayed",
    USERS: "",
    COMPLETION: "72%",
  },
  {
    PROJECT: "React Material Dashboard",
    BUDGET: "400 USD",
    STATUS: "on schedule",
    USERS: "",
    COMPLETION: "90%",
  },
  {
    PROJECT: "Vue Paper UI Kit PRO",
    BUDGET: "200 USD",
    STATUS: "completed",
    USERS: "",
    COMPLETION: "100%",
  },
];
